{
 "swagger": "2.0",
 "info": {
  "version": "0.2",
  "title": "MOKA API",
  "description": "MokaPOS core API documentation written in swagger-2.0 specification",
  "termsOfService": "https://www.mokapos.com/privacy",
  "contact": {
   "name": "MokaPOS API Team"
  },
  "license": {
   "name": "MokaPOS"
  },
  "x-logo": {
   "url": "https://i.gojekapi.com/darkroom/moka/v2/images/static/open-platform/logo-moka-v2.png"
  }
 },
 "host": "api.mokapos.com",
 "basePath": "",
 "tags": [
  {
   "name": "Types of Moka Apps",
   "description": "<p>Moka APIs let developers to create applications for various integration. Depending on the purpose of your app, it can be considered as a public or private app. The definition of each can be seen below:</p> <ul> <li><b>Public apps</b> are meant for developers who want to distribute their applications to many merchants of Moka</li> <li><b>Private apps</b> are meant for developers who want to build an integration specifically for a certain merchant or for personal use</li> </u[...]"
  },
  {
   "name": "Authentication",
   "description": "<h2>access_token</h2>\n<p>Access token for doing API request</p>\n<table class=\"security-details\">\n  <tbody>\n    <tr>\n      <th> Security scheme type: </th>\n      <td> OAuth2 </td>\n    </tr>\n    <tr>\n      <th> implicit OAuth Flow </th>\n      <td>\n        <div>\n          <strong> Authorization URL: </strong>/oauth/authorize\n        </div>\n        <div>\n          <strong> Scopes: </strong>\n        </div>\n        <ul>\n          <li>\n            <code>customer<[...]"
  },
  {
   "name": "Changelog",
   "description": "<p>These logs document the changes in Moka APIs including the supplemental and versioned changes. </p>\n<h2><b><p>Changelog history</p></b></h2>\n<hr style=\"height:1px;border:none;color:#333;background-color:#333;\">\n<h3><b><p>22-06-2023</p></b></h3>\n<hr style=\"height:1px;border:none;color:#333;background-color:#333;\">\n<h2><b><p>Features:</p></b></h2>\n<h3>Remove usage of below fields for following API: </h3>\n<ul>\n  <li><b></b>GET getEventsV1 API</p></li>\n  <li><b></b[...]"
  },
  {
   "name": "Loyalties",
   "description": "<p>Loyalty Program is related to business.</p>\n<p>These are the terminology of loyalty</p>\n<p>\n  <b>Customer and Merchant</b>\n  <p>Merchant is the owner of a business, and a user of Moka App. Customer will do transactions to merchant. There are 2 kind of customers, loyalty and non-loyalty.</p>\n  <p>A loyalty customer must have phone number</p>\n</p>\n<p>\n  <b>Program</b>\n</p>\n<p>When a merchant create a loyalty, he needs to first create a program. Currently we support [...]"
  },
  {
   "name": "Advanced Orderings",
   "description": "<p>Advanced orderings is an API that forwards the data to our mobile application. Using this API, 3rd party app can create a checkout using Moka</p>\n<p>There are various 3rd party which can consume this API, for example food delivery app and e-commerce.</p>\n<img src='https://i.gojekapi.com/darkroom/moka/v2/images/static/open-platform/api-docs/business-flow.png' height='500'/>\n<p>The diagram can be described as follows:</p>\n<ol>\n  <li>3rd party app create order using Moka [...]"
  },
  {
   "name": "Oauth",
   "description": "<img src='https://i.gojekapi.com/darkroom/moka/v2/images/static/open-platform/api-docs/auth-flow.png' height='400'/>\n<p>The flows is described as follows:</p>\n<ol>\n  <li>The owner of business (which uses Moka) open the <b>App Market</b></li>\n  <li>The owner see list of apps available in Moka</li>\n  <li>The user click <b>get started</b> to authorize the application</li>\n  <li>The backoffice redirect the user to the <b>authorization page</b></li>\n  <li>The <b>authorizatio[...]"
  },
  {
   "name": "Checkout API",
   "description": "<p>Checkout API is an API that allows merchants to send the transaction data from external source to Moka’s Backoffice.</p> <img src='https://i.gojekapi.com/darkroom/moka/v2/images/static/open-platform/api-docs/checkout_api_flow.png' height='100'/> <p>If the transaction includes discounted item, there are some restrictions to follow:</p> <ol> <li>If it is a <b>cash discount</b>, the information should be passed in the discount block</li> <img src='https://i.gojekapi.com/darkro[...]"
  },
  {
   "name": "Modification",
   "description": "<p>API for modification are API that allows merchants to supdate data to Moka’s Backoffice.</p>"
  }
 ],
 "x-tagGroups": [
  {
   "name": "Introduction",
   "tags": [
    "Getting Started",
    "Types of Moka Apps",
    "Authentication",
    "Changelog"
   ]
  },
  {
   "name": "Oauth",
   "tags": [
    "Oauth",
    "Subscription"
   ]
  },
  {
   "name": "Checkout",
   "tags": [
    "Advanced Orderings",
    "Checkout API"
   ]
  },
  {
   "name": "Modification",
   "tags": [
    "Item Adjustment"
   ]
  },
  {
   "name": "Get Merchant Profile",
   "tags": [
    "Business",
    "Customers",
    "Loyalties",
    "Outlet",
    "Users",
    "Quota"
   ]
  },
  {
   "name": "Read Library",
   "tags": [
    "Categories",
    "Discounts",
    "Favorites",
    "Gratuities",
    "Items",
    "Modifiers",
    "Taxes",
    "Purchase Order",
    "Sales Type",
    "Promos",
    "Bundle Package"
   ]
  },
  {
   "name": "Read Ingredient",
   "tags": [
    "Ingredient Categories",
    "Ingredient Library"
   ]
  },
  {
   "name": "Read Inventory",
   "tags": [
    "Item Summaries"
   ]
  },
  {
   "name": "Read Transaction",
   "tags": [
    "Invoices",
    "Latest Transaction",
    "Transaction",
    "Sync Bills"
   ]
  },
  {
   "name": "Get Reports",
   "tags": [
    "Category Sales",
    "Collector Sales",
    "Modifier Sales",
    "Discount Sales",
    "Tax Sales",
    "Gratuity Sales",
    "Server Sales",
    "Item Sales",
    "Sales summary",
    "Payment Methods"
   ]
  }
 ],
 "paths": {
  "/v4/outlets/{outlet_id}/reports/get_latest_transactions": {
   "get": {
    "security": [
     {
      "access_token": [
       "report"
      ]
     }
    ],
    "description": "Return all sales transactions of an outlet sorted by newest one first. Required permissions: `transaction`",
    "operationId": "showLatestTransactionsV4",
    "tags": [
     "Latest Transaction"
    ]
   }
  },
  "/v3/outlets/{outlet_id}/reports/item_sales": {
   "get": {
    "security": [
     {
      "access_token": [
       "report"
      ]
     }
    ],
    "description": "Show item sales for selected date range on the selected outlet. Required permissions: `report`",
    "operationId": "showItemSalesV3",
    "tags": [
     "Item Sales"
    ]
   }
  },
  "/v3/outlets/{outlet_id}/reports/invoices": {
   "get": {
    "security": [
     {
      "access_token": [
       "transaction"
      ]
     }
    ],
    "description": "Returns all the invoices of an outlet. Required permissions: `transaction`",
    "operationId": "reportInvoicesV3",
    "tags": [
     "Invoices"
    ]
   }
  },
  "/v3/outlets/{outlet_id}/reports/get_latest_transactions": {
   "get": {
    "security": [
     {
      "access_token": [
       "transaction"
      ]
     }
    ],
    "description": "Return all sales transactions of an outlet sorted by newest one first. Required permissions: `transaction`",
    "operationId": "showLatestTransactionsV3",
    "tags": [
     "Latest Transaction"
    ]
   }
  },
  "/v2/outlets/{outlet_id}/invoices/{invoice_id}": {
   "get": {
    "security": [
     {
      "access_token": [
       "transaction"
      ]
     }
    ],
    "description": "<b style='color:red'>Deprecated API. We will no longer provide support for reportInvoiceDetailV2. Please use reportInvoiceDetailV3.</b><br/>Returns an invoice based on the invoice ID. Required permissions: `transaction`",
    "operationId": "reportInvoiceDetailV2",
    "tags": [
     "Invoices"
    ]
   }
  },
  "/v3/outlets/{outlet_id}/invoices/{invoice_id}": {
   "get": {
    "security": [
     {
      "access_token": [
       "transaction"
      ]
     }
    ],
    "description": "Returns an invoice based on the invoice ID. Required permissions: `transaction`",
    "operationId": "reportInvoiceDetailV3",
    "tags": [
     "Invoices"
    ]
   }
  },
  "/v2/outlets/{outlet_id}/reports/category_sales": {
   "get": {
    "security": [
     {
      "access_token": [
       "report"
      ]
     }
    ],
    "description": "Show category sales for selected date range on the selected outlet. Required permissions: `report`",
    "operationId": "showCategorySalesV2",
    "tags": [
     "Category Sales"
    ]
   }
  },
  "/v2/outlets/{outlet_id}/reports/collector_sales": {
   "get": {
    "security": [
     {
      "access_token": [
       "report"
      ]
     }
    ],
    "description": "Return all sales sorted by collectors/collected_by/staffs for selected date range on the selected outlet. Required permissions: `report`",
    "operationId": "showCollectorSalesV2",
    "tags": [
     "Collector Sales"
    ]
   }
  },
  "/v2/outlets/{outlet_id}/reports/discount_sales": {
   "get": {
    "security": [
     {
      "access_token": [
       "report"
      ]
     }
    ],
    "description": "Return all sales sorted by discounts for selected date range on the selected outlet. Required permissions: `report`",
    "operationId": "showDiscountSalesV2",
    "tags": [
     "Discount Sales"
    ]
   }
  },
  "/v2/outlets/{outlet_id}/reports/gratuity_sales": {
   "get": {
    "security": [
     {
      "access_token": [
       "report"
      ]
     }
    ],
    "description": "Return all sales sorted by gratuity for selected date range on the selected outlet. Required permissions: `report`",
    "operationId": "showGratuitySalesV2",
    "tags": [
     "Gratuity Sales"
    ]
   }
  },
  "/v2/outlets/{outlet_id}/reports/item_sales": {
   "get": {
    "security": [
     {
      "access_token": [
       "report"
      ]
     }
    ],
    "description": "<b style='color:red'>Deprecated API. We will no longer provide support for showItemSalesV2. Please use showItemSalesV3.</b><br/>Show item sales for selected date range on the selected outlet. Required permissions: `report`",
    "operationId": "showItemSalesV2",
    "tags": [
     "Item Sales"
    ]
   }
  },
  "/v2/outlets/{outlet_id}/reports/modifier_sales": {
   "get": {
    "description": "Show modifier sales for selected date range on the selected outlet. Required permissions: `report`",
    "operationId": "showModifierSalesV2",
    "security": [
     {
      "access_token": [
       "report"
      ]
     }
    ],
    "tags": [
     "Modifier Sales"
    ]
   }
  },
  "/v2/outlets/{outlet_id}/reports/sales_summary": {
   "get": {
    "security": [
     {
      "access_token": [
       "report"
      ]
     }
    ],
    "description": "Returns summary of the sales for selected date range on the selected outlet. Required permissions: `report`",
    "operationId": "showSalesSummaryV2",
    "tags": [
     "Sales summary"
    ]
   }
  },
  "/v2/outlets/{outlet_id}/reports/server_sales": {
   "get": {
    "security": [
     {
      "access_token": [
       "report"
      ]
     }
    ],
    "description": "Return all sales sorted by servers for selected date range on the selected outlet. Required permissions: `report`",
    "operationId": "showServerSalesV2",
    "tags": [
     "Server Sales"
    ]
   }
  },
  "/v2/outlets/{outlet_id}/reports/payment_methods": {
   "get": {
    "security": [
     {
      "access_token": [
       "report"
      ]
     }
    ],
    "description": "Return all sales sorted by payment methods for selected date range on the selected outlet. Required permissions: `report`",
    "operationId": "showPaymentMethodsV2",
    "tags": [
     "Payment Methods"
    ]
   }
  },
  "/v2/outlets/{outlet_id}/reports/tax_sales": {
   "get": {
    "security": [
     {
      "access_token": [
       "report"
      ]
     }
    ],
    "description": "Returns all sales sorted by taxes for selected date range on the selected outlet. Required permissions: `report`",
    "operationId": "showTaxSalesV2",
    "tags": [
     "Tax Sales"
    ]
   }
  },
  "/v2/outlets/{outlet_id}/reports/transactions": {
   "get": {
    "security": [
     {
      "access_token": [
       "transaction"
      ]
     }
    ],
    "description": "<b style='color:red'>Deprecated API. We will no longer provide support for transactionsV2. Please use showLatestTransactionsV3.</b><br/>Return all transactions by outlet. Required permissions: `transaction`",
    "operationId": "transactionsV2",
    "tags": [
     "Transaction"
    ]
   }
  },
  "/v2/outlets/{outlet_id}/reports/invoices": {
   "get": {
    "security": [
     {
      "access_token": [
       "transaction"
      ]
     }
    ],
    "description": "<b style='color:red'>Deprecated API. We will no longer provide support for reportInvoicesV2. Please use reportInvoicesV3.</b><br/>Returns all the invoices of an outlet. Required permissions: `transaction`",
    "operationId": "reportInvoicesV2",
    "tags": [
     "Invoices"
    ]
   }
  },
  "/v2/outlets/{outlet_id}/reports/get_latest_transactions": {
   "get": {
    "security": [
     {
      "access_token": [
       "transaction"
      ]
     }
    ],
    "description": "<b style='color:red'>Deprecated API. We will no longer provide support for showLatestTransactionsV2. Please use showLatestTransactionsV3.</b><br/>Return all sales transactions of an outlet sorted by newest one first. Required permissions: `transaction`",
    "operationId": "showLatestTransactionsV2",
    "tags": [
     "Latest Transaction"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/advanced_orderings/orders": {
   "post": {
    "security": [
     {
      "access_token": [
       "checkout"
      ]
     }
    ],
    "description": "Create orders to outlet. Required permissions: `checkout`",
    "operationId": "createOrderV1",
    "tags": [
     "Advanced Orderings"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/advanced_orderings/orders/{application_order_id}/cancel": {
   "post": {
    "security": [
     {
      "access_token": [
       "checkout"
      ]
     }
    ],
    "description": "Cancel order to outlet. Required permissions: `checkout`",
    "operationId": "cancelOrderV1",
    "tags": [
     "Advanced Orderings"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/advanced_orderings/orders/{application_order_id}/status": {
   "get": {
    "security": [
     {
      "access_token": [
       "checkout"
      ]
     }
    ],
    "description": " Retrieves an order's status. Required permissions: `checkout` <div>\n  <br>\n  <div>\n  This will return the order’s status code, the status code is a predefined set of code strings described as follows:\n  </div>\n  <br>\n  <table>\n    <tr>\n      <th>Order Status Code</th>\n      <th>Short Description</th>\n      <th>Description</th>\n    </tr>\n    <tr>\n      <td> <b>\"0\"</b> </td>\n      <td> INCOMING </td>\n      <td> The order notification was sent to the merchant a[...]",
    "operationId": "getOrderStatusV1",
    "tags": [
     "Advanced Orderings"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/advanced_orderings/generate_sales_type": {
   "post": {
    "description": "<p> Generate Advanced Orderings sales type for an outlet. </p> <p> Required Permissions: `sales_type` `library` </p>",
    "operationId": "generateSalesTypeV1",
    "tags": [
     "Advanced Orderings"
    ],
    "security": [
     {
      "access_token": [
       "checkout"
      ]
     }
    ]
   }
  },
  "/v2/outlets/{outlet_id}/advanced_orderings/generate_sales_type": {
   "post": {
    "description": "<p> Generate Advanced Orderings sales type for an outlet. </p> <p> Required Permissions: `sales_type` `library` </p>",
    "operationId": "generateSalesTypeV2",
    "tags": [
     "Advanced Orderings"
    ],
    "security": [
     {
      "access_token": [
       "checkout"
      ]
     }
    ]
   }
  },
  "/v1/outlets/{outlet_id}/advanced_orderings/auto_accept": {
   "get": {
    "security": [
     {
      "access_token": [
       "checkout"
      ]
     }
    ],
    "description": "Retrieve auto accept status of an outlet. Required permissions: `checkout`",
    "operationId": "getAutoAcceptV1",
    "tags": [
     "Advanced Orderings"
    ]
   },
   "post": {
    "security": [
     {
      "access_token": [
       "checkout"
      ]
     }
    ],
    "description": "Set auto accept feature of an outlet. Required permissions: `checkout`<div>\n  <div>\n    Auto accept feature allows the merchant to receive incoming order without the needs of accepting it. The boolean is defined as follows:\n  </div>\n  <table>\n    <tr>\n      <th>Auto Accept Status</th>\n      <th>Description</th>\n    </tr>\n    <tr>\n      <td>ON</td>\n      <td>Incoming orders will be automatically accepted. Merchant only need to complete an order.</td>\n    </tr>\n   [...]",
    "operationId": "setAutoAcceptV1",
    "tags": [
     "Advanced Orderings"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/advanced_orderings/orders/{application_order_id}/drivers": {
   "post": {
    "security": [
     {
      "access_token": [
       "checkout"
      ]
     }
    ],
    "description": "Updates online order based on the online order ID. Required permissions: `checkout`",
    "operationId": "updateOrderDriverV1",
    "tags": [
     "Advanced Orderings"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/bundle_package": {
   "get": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Returns all bundle packages on the outlet that the user has access to. Required permissions: `library`",
    "operationId": "listBundlePackagesV1",
    "tags": [
     "Bundle Package"
    ]
   }
  },
  "/v1/businesses": {
   "get": {
    "security": [
     {
      "access_token": [
       "profile"
      ]
     }
    ],
    "description": "Returns the merchant's business information. Required permissions: `profile`",
    "operationId": "showBusinessInformationV1",
    "tags": [
     "Business"
    ]
   }
  },
  "/v1/businesses/{business_id}/checkout_settings": {
   "get": {
    "security": [
     {
      "access_token": [
       "profile"
      ]
     }
    ],
    "description": "Retrieve the checkout settings of a business. Required permissions: `profile`",
    "operationId": "getBusinessCheckoutSettingsV1",
    "tags": [
     "Business"
    ]
   }
  },
  "/v1/businesses/{business_id}/customers": {
   "get": {
    "security": [
     {
      "access_token": [
       "customer"
      ]
     }
    ],
    "description": "Returns all customers on the outlet that the user has access to. Required permissions: `customer`",
    "operationId": "listCustomersV1",
    "tags": [
     "Customers"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/categories": {
   "get": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Returns all categories on the outlet that the user has access to. Required permissions: `library`",
    "operationId": "listCategoriesV1",
    "tags": [
     "Categories"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/discounts": {
   "get": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Returns all discounts on the outlet that the user has access to. Required permissions: `library`",
    "operationId": "listDiscountsV1",
    "tags": [
     "Discounts"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/favorites": {
   "get": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "<b style='color:red'>Deprecated API.</b>",
    "operationId": "listFavoritesV1",
    "tags": [
     "Favorites"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/gratuities": {
   "get": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Returns all gratuities on the outlet that the user has access to. Required permissions: `library`",
    "operationId": "listGratuitiesV1",
    "tags": [
     "Gratuities"
    ]
   }
  },
  "/v1/businesses/{business_id}/loyalties/programs": {
   "get": {
    "security": [
     {
      "access_token": [
       "customer"
      ]
     }
    ],
    "description": "Returns all the loyalties programs of a merchant. Required permissions: `customer`",
    "operationId": "showLoyaltyProgramV1",
    "tags": [
     "Loyalties"
    ]
   }
  },
  "/v1/loyalties/point-activities": {
   "get": {
    "security": [
     {
      "access_token": [
       "customer"
      ]
     }
    ],
    "description": "Returns loyalty point activities for a customer. Required permissions: `customer`",
    "operationId": "showLoyaltyPointActivitiesV1",
    "tags": [
     "Loyalties"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/ingredients/categories": {
   "get": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Returns all ingredient categories on the outlet that the user has access to. Required permissions: `library`",
    "operationId": "listIngredientCategoriesV1",
    "tags": [
     "Ingredient Categories"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/ingredients/library": {
   "get": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Returns the ingredient library on the outlet that the user has access to. Required permissions: `library`",
    "operationId": "listIngredientLibraryV1",
    "tags": [
     "Ingredient Library"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/items": {
   "get": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Returns all items on the outlet that the user has access to. Required permissions: `library`",
    "operationId": "listItemsV1",
    "tags": [
     "Items"
    ]
   },
   "post": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Create items library. Required permissions: `library`",
    "operationId": "createItemV1",
    "tags": [
     "Items"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/items/{item_id}": {
   "put": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Update items library. Required permissions: `library`",
    "operationId": "updateItemV1",
    "tags": [
     "Items"
    ]
   },
   "delete": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Delete items library. Required permissions: `library`",
    "operationId": "deleteItemV1",
    "tags": [
     "Items"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/items/image": {
   "post": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Upload item POS image. Required permissions: `library`",
    "operationId": "uploadPOSImageV1",
    "tags": [
     "Items"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/items/ecommerce-image": {
   "post": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Upload item E-commerce image. Required permissions: `library`",
    "operationId": "uploadEcommerceImageV1",
    "tags": [
     "Items"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/modifiers": {
   "get": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Returns all modifiers on the outlet that the user has access to. Required permissions: `library`",
    "operationId": "listModifiersV1",
    "tags": [
     "Modifiers"
    ]
   }
  },
  "/v1/businesses/{business_id}/outlets": {
   "get": {
    "security": [
     {
      "access_token": [
       "profile"
      ]
     }
    ],
    "description": "Returns current user outlets information. Required permissions: `profile`",
    "operationId": "listOutletsInformationV1",
    "tags": [
     "Outlet"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/reports/get_latest_transactions": {
   "get": {
    "security": [
     {
      "access_token": [
       "transaction"
      ]
     }
    ],
    "description": "<b style='color:red'>Deprecated API. We will no longer provide support for showLatestTransactionsV1. Please use showLatestTransactionsV2.</b><br/>:Returns all sales transactions of an outlet sorted by the newest one first. Required permissions: `transaction`",
    "operationId": "showLatestTransactionsV1",
    "tags": [
     "Latest Transaction"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/reports/transactions": {
   "get": {
    "security": [
     {
      "access_token": [
       "transaction"
      ]
     }
    ],
    "description": "<b style='color:red'>Deprecated API. We will no longer provide support for showTransactionsV1. Please use showLatestTransactionsV2.</b><br/>Return all sales transactions for selected date range on the selected outlet. Required permissions: `transaction`",
    "operationId": "showTransactionsV1",
    "tags": [
     "Transaction"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/reports/sales_types": {
   "get": {
    "security": [
     {
      "access_token": [
       "report"
      ]
     }
    ],
    "description": "Returns sales report for each sales type on an outlet. Required permissions: `report`",
    "operationId": "salesTypeReport",
    "tags": [
     "Sales Type"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/taxes": {
   "get": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Returns all taxes on the outlet that the user has access to. Required permissions: `library`",
    "operationId": "listTaxesV1",
    "tags": [
     "Taxes"
    ]
   }
  },
  "/v1/profile/self": {
   "get": {
    "security": [
     {
      "access_token": [
       "profile"
      ]
     }
    ],
    "description": "Returns current user information that logged in. Required permissions: `profile`",
    "operationId": "showUserInformation",
    "tags": [
     "Users"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/sales_type": {
   "get": {
    "security": [
     {
      "access_token": [
       "profile"
      ]
     }
    ],
    "description": "Return all sales type on a merchant's outlet. Required permissions: `library`",
    "operationId": "listSalesType",
    "tags": [
     "Sales Type"
    ]
   },
   "post": {
    "security": [
     {
      "access_token": [
       "profile"
      ]
     }
    ],
    "description": "Create sales type on a specified merchant's outlet. Required permissions: `library`",
    "operationId": "createSalesType",
    "tags": [
     "Sales Type"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/sales_type/{id}": {
   "get": {
    "security": [
     {
      "access_token": [
       "profile"
      ]
     }
    ],
    "description": "Return the detail of a sales type in a merchant's outlet. Required permissions: `library`",
    "operationId": "salesTypeDetail",
    "tags": [
     "Sales Type"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/sync_bills/": {
   "get": {
    "security": [
     {
      "access_token": [
       "transaction"
      ]
     }
    ],
    "description": "Returns all open bill list of an outlet.",
    "operationId": "listBillsV1",
    "tags": [
     "Sync Bills"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/sync_bills/{bill_id}": {
   "get": {
    "security": [
     {
      "access_token": [
       "transaction"
      ]
     }
    ],
    "description": "Returns the detail of a bill given a bill ID.",
    "operationId": "listBillByIDV1",
    "tags": [
     "Sync Bills"
    ]
   }
  },
  "/v1/quotas": {
   "get": {
    "security": [
     {
      "access_token": [
       "profile"
      ]
     }
    ],
    "description": "Returns remaining quota of an outlet when calling certain API.",
    "operationId": "showQuotaInformationV1",
    "tags": [
     "Quota"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/promos": {
   "get": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Returns all promos on the outlets that the user has access to. Required permissions: `library`<br/><br/><b>NOTE:</b> `promo_status` may be displayed as active even though the current date and time is not between `promo_start_date` and `promo_end_date`.<br/><br/>\nIf a promo is not deactivated in Backoffice and current date is not in range between `start_date` and `end_date`, then `promo_status` will be Active. However, we treat this type of promo as Inactive in Backoffice. Th[...]",
    "operationId": "listPromosV1",
    "tags": [
     "Promos"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/inventory/purchase_orders/{id}": {
   "get": {
    "security": [
     {
      "access_token": [
       "profile"
      ]
     }
    ],
    "description": "Returns a Purchase Order by ID.  Required permissions: `library`<br/><br/><b>NOTE:</b> Results are sorted by created_at and in descending order.",
    "operationId": "listPurchaseOrderByIDV1",
    "tags": [
     "Purchase Order"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/inventory/purchase_orders": {
   "get": {
    "security": [
     {
      "access_token": [
       "profile"
      ]
     }
    ],
    "description": "Returns a list of purchase orders on a time interval.  Required permissions: `library`",
    "operationId": "purchaseOrdersV1",
    "tags": [
     "Purchase Order"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/inventory/ingredient_purchase_orders/{id}": {
   "get": {
    "security": [
     {
      "access_token": [
       "profile"
      ]
     }
    ],
    "description": "Returns an ingredients Purchase Order by ID. Required permissions: `library`",
    "operationId": "listIngredientPurchaseOrderByIDV1",
    "tags": [
     "Purchase Order"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/inventory/ingredient_purchase_orders": {
   "get": {
    "security": [
     {
      "access_token": [
       "profile"
      ]
     }
    ],
    "description": "Returns a list of ingredient purchase orders on a time interval.  Required permissions: `library`",
    "operationId": "ingredientPurchaseOrdersV1",
    "tags": [
     "Purchase Order"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/checkouts": {
   "post": {
    "security": [
     {
      "access_token": [
       "checkout_api"
      ]
     }
    ],
    "description": "Create checkout to outlet. Required permissions: `checkout_api`",
    "operationId": "createCheckoutV1",
    "tags": [
     "Checkout API"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/adjustment/items": {
   "post": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Create item adjustment for items. Required permissions: `library`",
    "operationId": "createItemAdjustmentV1",
    "tags": [
     "Item Adjustment"
    ]
   }
  },
  "/v1/outlets/{outlet_id}/inventory/item_summaries": {
   "get": {
    "security": [
     {
      "access_token": [
       "library"
      ]
     }
    ],
    "description": "Required permissions: `library`. Item Summaries summarize item variant's stock at the beginning of the day, end of day, and sum of every transaction that happened\n            within a certain date period.\n            A record of summary will be created for an item variant for this condition :\n\n- An item variant is created with track_stock true\n- An item variant is updated to track_stock true and never been set to true before\n- A transaction for an item variant is create[...]",
    "operationId": "listItemSummariesV1",
    "tags": [
     "Item Summaries"
    ]
   }
  },
  "/oauth/revoke": {
   "post": {
    "security": [
     {
      "access_token": [
       ""
      ]
     }
    ],
    "description": "Revoke given token. After this operation, the given token cannot be used anymore",
    "operationId": "revokeToken",
    "tags": [
     "Oauth"
    ]
   }
  },
  "/oauth/token": {
   "post": {
    "security": [
     {
      "access_token": [
       ""
      ]
     }
    ],
    "description": "Change grant token into access token or refresh access token",
    "operationId": "exchangeToken",
    "tags": [
     "Oauth"
    ]
   }
  }
 }
}